//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.UserServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddUserContract", Namespace="http://schemas.datacontract.org/2004/07/PruebaTecnica.Business.DataContracts.Requ" +
        "ests")]
    [System.SerializableAttribute()]
    public partial class AddUserContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime birth_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime birth_date {
            get {
                return this.birth_dateField;
            }
            set {
                if ((this.birth_dateField.Equals(value) != true)) {
                    this.birth_dateField = value;
                    this.RaisePropertyChanged("birth_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char gender {
            get {
                return this.genderField;
            }
            set {
                if ((this.genderField.Equals(value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponseOfAddUserResponsedqZ23X9b", Namespace="http://schemas.datacontract.org/2004/07/PruebaTecnica.Business.DataContracts.Resp" +
        "onses")]
    [System.SerializableAttribute()]
    public partial class BaseResponseOfAddUserResponsedqZ23X9b : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int response_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] errorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.UserServiceReference.AddUserResponse resultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int response_code {
            get {
                return this.response_codeField;
            }
            set {
                if ((this.response_codeField.Equals(value) != true)) {
                    this.response_codeField = value;
                    this.RaisePropertyChanged("response_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool is_success {
            get {
                return this.is_successField;
            }
            set {
                if ((this.is_successField.Equals(value) != true)) {
                    this.is_successField = value;
                    this.RaisePropertyChanged("is_success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string[] errors {
            get {
                return this.errorsField;
            }
            set {
                if ((object.ReferenceEquals(this.errorsField, value) != true)) {
                    this.errorsField = value;
                    this.RaisePropertyChanged("errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Presentation.UserServiceReference.AddUserResponse result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddUserResponse", Namespace="http://schemas.datacontract.org/2004/07/PruebaTecnica.Business.DataContracts.Resp" +
        "onses")]
    [System.SerializableAttribute()]
    public partial class AddUserResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int user_added_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_added_id {
            get {
                return this.user_added_idField;
            }
            set {
                if ((this.user_added_idField.Equals(value) != true)) {
                    this.user_added_idField = value;
                    this.RaisePropertyChanged("user_added_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUserByIdContract", Namespace="http://schemas.datacontract.org/2004/07/PruebaTecnica.Business.DataContracts.Requ" +
        "ests")]
    [System.SerializableAttribute()]
    public partial class GetUserByIdContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int user_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponseOfUserDtodqZ23X9b", Namespace="http://schemas.datacontract.org/2004/07/PruebaTecnica.Business.DataContracts.Resp" +
        "onses")]
    [System.SerializableAttribute()]
    public partial class BaseResponseOfUserDtodqZ23X9b : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int response_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] errorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.UserServiceReference.UserDto resultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int response_code {
            get {
                return this.response_codeField;
            }
            set {
                if ((this.response_codeField.Equals(value) != true)) {
                    this.response_codeField = value;
                    this.RaisePropertyChanged("response_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool is_success {
            get {
                return this.is_successField;
            }
            set {
                if ((this.is_successField.Equals(value) != true)) {
                    this.is_successField = value;
                    this.RaisePropertyChanged("is_success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string[] errors {
            get {
                return this.errorsField;
            }
            set {
                if ((object.ReferenceEquals(this.errorsField, value) != true)) {
                    this.errorsField = value;
                    this.RaisePropertyChanged("errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Presentation.UserServiceReference.UserDto result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://schemas.datacontract.org/2004/07/PruebaTecnica.Business.DataContracts.Resp" +
        "onses")]
    [System.SerializableAttribute()]
    public partial class UserDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime birth_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char genderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime birth_date {
            get {
                return this.birth_dateField;
            }
            set {
                if ((this.birth_dateField.Equals(value) != true)) {
                    this.birth_dateField = value;
                    this.RaisePropertyChanged("birth_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public char gender {
            get {
                return this.genderField;
            }
            set {
                if ((this.genderField.Equals(value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUsersPaginatedContract", Namespace="http://schemas.datacontract.org/2004/07/PruebaTecnica.Business.DataContracts.Requ" +
        "ests")]
    [System.SerializableAttribute()]
    public partial class GetUsersPaginatedContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int current_pageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool order_descField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int page_sizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int current_page {
            get {
                return this.current_pageField;
            }
            set {
                if ((this.current_pageField.Equals(value) != true)) {
                    this.current_pageField = value;
                    this.RaisePropertyChanged("current_page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool order_desc {
            get {
                return this.order_descField;
            }
            set {
                if ((this.order_descField.Equals(value) != true)) {
                    this.order_descField = value;
                    this.RaisePropertyChanged("order_desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int page_size {
            get {
                return this.page_sizeField;
            }
            set {
                if ((this.page_sizeField.Equals(value) != true)) {
                    this.page_sizeField = value;
                    this.RaisePropertyChanged("page_size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponseOfGetUsersPaginatedResponsedqZ23X9b", Namespace="http://schemas.datacontract.org/2004/07/PruebaTecnica.Business.DataContracts.Resp" +
        "onses")]
    [System.SerializableAttribute()]
    public partial class BaseResponseOfGetUsersPaginatedResponsedqZ23X9b : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int response_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] errorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.UserServiceReference.GetUsersPaginatedResponse resultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int response_code {
            get {
                return this.response_codeField;
            }
            set {
                if ((this.response_codeField.Equals(value) != true)) {
                    this.response_codeField = value;
                    this.RaisePropertyChanged("response_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool is_success {
            get {
                return this.is_successField;
            }
            set {
                if ((this.is_successField.Equals(value) != true)) {
                    this.is_successField = value;
                    this.RaisePropertyChanged("is_success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string[] errors {
            get {
                return this.errorsField;
            }
            set {
                if ((object.ReferenceEquals(this.errorsField, value) != true)) {
                    this.errorsField = value;
                    this.RaisePropertyChanged("errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Presentation.UserServiceReference.GetUsersPaginatedResponse result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUsersPaginatedResponse", Namespace="http://schemas.datacontract.org/2004/07/PruebaTecnica.Business.DataContracts.Resp" +
        "onses")]
    [System.SerializableAttribute()]
    public partial class GetUsersPaginatedResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.UserServiceReference.UserDto[] usersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int total_usersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int current_pageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int page_sizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Presentation.UserServiceReference.UserDto[] users {
            get {
                return this.usersField;
            }
            set {
                if ((object.ReferenceEquals(this.usersField, value) != true)) {
                    this.usersField = value;
                    this.RaisePropertyChanged("users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int total_users {
            get {
                return this.total_usersField;
            }
            set {
                if ((this.total_usersField.Equals(value) != true)) {
                    this.total_usersField = value;
                    this.RaisePropertyChanged("total_users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int current_page {
            get {
                return this.current_pageField;
            }
            set {
                if ((this.current_pageField.Equals(value) != true)) {
                    this.current_pageField = value;
                    this.RaisePropertyChanged("current_page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int page_size {
            get {
                return this.page_sizeField;
            }
            set {
                if ((this.page_sizeField.Equals(value) != true)) {
                    this.page_sizeField = value;
                    this.RaisePropertyChanged("page_size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUsersByNamePaginatedContract", Namespace="http://schemas.datacontract.org/2004/07/PruebaTecnica.Business.DataContracts.Requ" +
        "ests")]
    [System.SerializableAttribute()]
    public partial class GetUsersByNamePaginatedContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int current_pageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool order_descField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int page_sizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int current_page {
            get {
                return this.current_pageField;
            }
            set {
                if ((this.current_pageField.Equals(value) != true)) {
                    this.current_pageField = value;
                    this.RaisePropertyChanged("current_page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool order_desc {
            get {
                return this.order_descField;
            }
            set {
                if ((this.order_descField.Equals(value) != true)) {
                    this.order_descField = value;
                    this.RaisePropertyChanged("order_desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int page_size {
            get {
                return this.page_sizeField;
            }
            set {
                if ((this.page_sizeField.Equals(value) != true)) {
                    this.page_sizeField = value;
                    this.RaisePropertyChanged("page_size");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateUserContract", Namespace="http://schemas.datacontract.org/2004/07/PruebaTecnica.Business.DataContracts.Requ" +
        "ests")]
    [System.SerializableAttribute()]
    public partial class UpdateUserContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime birth_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int user_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime birth_date {
            get {
                return this.birth_dateField;
            }
            set {
                if ((this.birth_dateField.Equals(value) != true)) {
                    this.birth_dateField = value;
                    this.RaisePropertyChanged("birth_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char gender {
            get {
                return this.genderField;
            }
            set {
                if ((this.genderField.Equals(value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponseOfUpdateUserResponsedqZ23X9b", Namespace="http://schemas.datacontract.org/2004/07/PruebaTecnica.Business.DataContracts.Resp" +
        "onses")]
    [System.SerializableAttribute()]
    public partial class BaseResponseOfUpdateUserResponsedqZ23X9b : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int response_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] errorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.UserServiceReference.UpdateUserResponse resultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int response_code {
            get {
                return this.response_codeField;
            }
            set {
                if ((this.response_codeField.Equals(value) != true)) {
                    this.response_codeField = value;
                    this.RaisePropertyChanged("response_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool is_success {
            get {
                return this.is_successField;
            }
            set {
                if ((this.is_successField.Equals(value) != true)) {
                    this.is_successField = value;
                    this.RaisePropertyChanged("is_success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string[] errors {
            get {
                return this.errorsField;
            }
            set {
                if ((object.ReferenceEquals(this.errorsField, value) != true)) {
                    this.errorsField = value;
                    this.RaisePropertyChanged("errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Presentation.UserServiceReference.UpdateUserResponse result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateUserResponse", Namespace="http://schemas.datacontract.org/2004/07/PruebaTecnica.Business.DataContracts.Resp" +
        "onses")]
    [System.SerializableAttribute()]
    public partial class UpdateUserResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int user_updated_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_updated_id {
            get {
                return this.user_updated_idField;
            }
            set {
                if ((this.user_updated_idField.Equals(value) != true)) {
                    this.user_updated_idField = value;
                    this.RaisePropertyChanged("user_updated_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteUserContract", Namespace="http://schemas.datacontract.org/2004/07/PruebaTecnica.Business.DataContracts.Requ" +
        "ests")]
    [System.SerializableAttribute()]
    public partial class DeleteUserContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int user_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponseOfDeleteUserResponsedqZ23X9b", Namespace="http://schemas.datacontract.org/2004/07/PruebaTecnica.Business.DataContracts.Resp" +
        "onses")]
    [System.SerializableAttribute()]
    public partial class BaseResponseOfDeleteUserResponsedqZ23X9b : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int response_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] errorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Presentation.UserServiceReference.DeleteUserResponse resultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int response_code {
            get {
                return this.response_codeField;
            }
            set {
                if ((this.response_codeField.Equals(value) != true)) {
                    this.response_codeField = value;
                    this.RaisePropertyChanged("response_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool is_success {
            get {
                return this.is_successField;
            }
            set {
                if ((this.is_successField.Equals(value) != true)) {
                    this.is_successField = value;
                    this.RaisePropertyChanged("is_success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string[] errors {
            get {
                return this.errorsField;
            }
            set {
                if ((object.ReferenceEquals(this.errorsField, value) != true)) {
                    this.errorsField = value;
                    this.RaisePropertyChanged("errors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public Presentation.UserServiceReference.DeleteUserResponse result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteUserResponse", Namespace="http://schemas.datacontract.org/2004/07/PruebaTecnica.Business.DataContracts.Resp" +
        "onses")]
    [System.SerializableAttribute()]
    public partial class DeleteUserResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int user_deleted_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_deleted_id {
            get {
                return this.user_deleted_idField;
            }
            set {
                if ((this.user_deleted_idField.Equals(value) != true)) {
                    this.user_deleted_idField = value;
                    this.RaisePropertyChanged("user_deleted_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddUser", ReplyAction="http://tempuri.org/IUserService/AddUserResponse")]
        Presentation.UserServiceReference.BaseResponseOfAddUserResponsedqZ23X9b AddUser(Presentation.UserServiceReference.AddUserContract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddUser", ReplyAction="http://tempuri.org/IUserService/AddUserResponse")]
        System.Threading.Tasks.Task<Presentation.UserServiceReference.BaseResponseOfAddUserResponsedqZ23X9b> AddUserAsync(Presentation.UserServiceReference.AddUserContract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserById", ReplyAction="http://tempuri.org/IUserService/GetUserByIdResponse")]
        Presentation.UserServiceReference.BaseResponseOfUserDtodqZ23X9b GetUserById(Presentation.UserServiceReference.GetUserByIdContract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserById", ReplyAction="http://tempuri.org/IUserService/GetUserByIdResponse")]
        System.Threading.Tasks.Task<Presentation.UserServiceReference.BaseResponseOfUserDtodqZ23X9b> GetUserByIdAsync(Presentation.UserServiceReference.GetUserByIdContract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsersPaginated", ReplyAction="http://tempuri.org/IUserService/GetUsersPaginatedResponse")]
        Presentation.UserServiceReference.BaseResponseOfGetUsersPaginatedResponsedqZ23X9b GetUsersPaginated(Presentation.UserServiceReference.GetUsersPaginatedContract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsersPaginated", ReplyAction="http://tempuri.org/IUserService/GetUsersPaginatedResponse")]
        System.Threading.Tasks.Task<Presentation.UserServiceReference.BaseResponseOfGetUsersPaginatedResponsedqZ23X9b> GetUsersPaginatedAsync(Presentation.UserServiceReference.GetUsersPaginatedContract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsersByNamePaginated", ReplyAction="http://tempuri.org/IUserService/GetUsersByNamePaginatedResponse")]
        Presentation.UserServiceReference.BaseResponseOfGetUsersPaginatedResponsedqZ23X9b GetUsersByNamePaginated(Presentation.UserServiceReference.GetUsersByNamePaginatedContract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsersByNamePaginated", ReplyAction="http://tempuri.org/IUserService/GetUsersByNamePaginatedResponse")]
        System.Threading.Tasks.Task<Presentation.UserServiceReference.BaseResponseOfGetUsersPaginatedResponsedqZ23X9b> GetUsersByNamePaginatedAsync(Presentation.UserServiceReference.GetUsersByNamePaginatedContract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        Presentation.UserServiceReference.BaseResponseOfUpdateUserResponsedqZ23X9b UpdateUser(Presentation.UserServiceReference.UpdateUserContract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/UpdateUser", ReplyAction="http://tempuri.org/IUserService/UpdateUserResponse")]
        System.Threading.Tasks.Task<Presentation.UserServiceReference.BaseResponseOfUpdateUserResponsedqZ23X9b> UpdateUserAsync(Presentation.UserServiceReference.UpdateUserContract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUser", ReplyAction="http://tempuri.org/IUserService/DeleteUserResponse")]
        Presentation.UserServiceReference.BaseResponseOfDeleteUserResponsedqZ23X9b DeleteUser(Presentation.UserServiceReference.DeleteUserContract contract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/DeleteUser", ReplyAction="http://tempuri.org/IUserService/DeleteUserResponse")]
        System.Threading.Tasks.Task<Presentation.UserServiceReference.BaseResponseOfDeleteUserResponsedqZ23X9b> DeleteUserAsync(Presentation.UserServiceReference.DeleteUserContract contract);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : Presentation.UserServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<Presentation.UserServiceReference.IUserService>, Presentation.UserServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Presentation.UserServiceReference.BaseResponseOfAddUserResponsedqZ23X9b AddUser(Presentation.UserServiceReference.AddUserContract contract) {
            return base.Channel.AddUser(contract);
        }
        
        public System.Threading.Tasks.Task<Presentation.UserServiceReference.BaseResponseOfAddUserResponsedqZ23X9b> AddUserAsync(Presentation.UserServiceReference.AddUserContract contract) {
            return base.Channel.AddUserAsync(contract);
        }
        
        public Presentation.UserServiceReference.BaseResponseOfUserDtodqZ23X9b GetUserById(Presentation.UserServiceReference.GetUserByIdContract contract) {
            return base.Channel.GetUserById(contract);
        }
        
        public System.Threading.Tasks.Task<Presentation.UserServiceReference.BaseResponseOfUserDtodqZ23X9b> GetUserByIdAsync(Presentation.UserServiceReference.GetUserByIdContract contract) {
            return base.Channel.GetUserByIdAsync(contract);
        }
        
        public Presentation.UserServiceReference.BaseResponseOfGetUsersPaginatedResponsedqZ23X9b GetUsersPaginated(Presentation.UserServiceReference.GetUsersPaginatedContract contract) {
            return base.Channel.GetUsersPaginated(contract);
        }
        
        public System.Threading.Tasks.Task<Presentation.UserServiceReference.BaseResponseOfGetUsersPaginatedResponsedqZ23X9b> GetUsersPaginatedAsync(Presentation.UserServiceReference.GetUsersPaginatedContract contract) {
            return base.Channel.GetUsersPaginatedAsync(contract);
        }
        
        public Presentation.UserServiceReference.BaseResponseOfGetUsersPaginatedResponsedqZ23X9b GetUsersByNamePaginated(Presentation.UserServiceReference.GetUsersByNamePaginatedContract contract) {
            return base.Channel.GetUsersByNamePaginated(contract);
        }
        
        public System.Threading.Tasks.Task<Presentation.UserServiceReference.BaseResponseOfGetUsersPaginatedResponsedqZ23X9b> GetUsersByNamePaginatedAsync(Presentation.UserServiceReference.GetUsersByNamePaginatedContract contract) {
            return base.Channel.GetUsersByNamePaginatedAsync(contract);
        }
        
        public Presentation.UserServiceReference.BaseResponseOfUpdateUserResponsedqZ23X9b UpdateUser(Presentation.UserServiceReference.UpdateUserContract contract) {
            return base.Channel.UpdateUser(contract);
        }
        
        public System.Threading.Tasks.Task<Presentation.UserServiceReference.BaseResponseOfUpdateUserResponsedqZ23X9b> UpdateUserAsync(Presentation.UserServiceReference.UpdateUserContract contract) {
            return base.Channel.UpdateUserAsync(contract);
        }
        
        public Presentation.UserServiceReference.BaseResponseOfDeleteUserResponsedqZ23X9b DeleteUser(Presentation.UserServiceReference.DeleteUserContract contract) {
            return base.Channel.DeleteUser(contract);
        }
        
        public System.Threading.Tasks.Task<Presentation.UserServiceReference.BaseResponseOfDeleteUserResponsedqZ23X9b> DeleteUserAsync(Presentation.UserServiceReference.DeleteUserContract contract) {
            return base.Channel.DeleteUserAsync(contract);
        }
    }
}
